name = "VectorCalculus"
uuid = "09f7b93a-2526-5221-9287-2354b873794c"
author = "Luke Stagner <stagnerl@fusion.gat.com>"
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "^1.2"
